<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CryptoScanner.Core\CryptoScanner.Core.csproj" />
    <ProjectReference Include="..\CryptoScanner.Indicators\CryptoScanner.Indicators.csproj" />
    <ProjectReference Include="..\CryptoScanner.Strategies\CryptoScanner.Strategies.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
